CREATE TABLE games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    release_date DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_games_external_id UNIQUE (external_id)
);

CREATE TABLE game_genres (
    game_id BIGINT NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    genre VARCHAR(64) NOT NULL,
    CONSTRAINT pk_game_genres PRIMARY KEY (game_id, genre)
);

CREATE TABLE game_tags (
    game_id BIGINT NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    tag VARCHAR(64) NOT NULL,
    CONSTRAINT pk_game_tags PRIMARY KEY (game_id, tag)
);

CREATE INDEX idx_game_genres_genre ON game_genres (genre);
CREATE INDEX idx_game_tags_tag ON game_tags (tag);
