CREATE TABLE library_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    game_id BIGINT NOT NULL REFERENCES games (id) ON DELETE CASCADE,
    status VARCHAR(16) NOT NULL DEFAULT 'BACKLOG',
    total_playtime_minutes INTEGER NOT NULL DEFAULT 0,
    last_played_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT uk_library_entries_user_game UNIQUE (user_id, game_id),
    CONSTRAINT ck_library_entries_status
        CHECK (status IN ('BACKLOG','PLAYING','FINISHED','DROPPED','BOUNCED')),
    CONSTRAINT ck_library_entries_playtime_non_negative
        CHECK (total_playtime_minutes >= 0)
);

CREATE INDEX idx_library_entries_user_id ON library_entries (user_id);
CREATE INDEX idx_library_entries_game_id ON library_entries (game_id);
CREATE INDEX idx_library_entries_status ON library_entries (status);
